### ISSUE TITLE
Cannot read property 'userAgent' of undefinded?

### ISSUE THREAD

**Issue by Sprtcrnbry** [KurozeroPB/AzurLane#2]
I integrated the API to my Discord bot, tried running it, and this happened:
```
/home/sprtcrnbry/tools/BukanGC56/node_modules/azurlane/lib/index.js:60
        this.options.userAgent = options.userAgent ? options.userAgent : "AzurLane/v1.6.0 (https://www.npmjs.com/package/azurlane)";
                                         ^

TypeError: Cannot read property 'userAgent' of undefined
    at new AzurLane (/home/sprtcrnbry/tools/BukanGC56/node_modules/azurlane/lib/index.js:60:42)
    at Object.<anonymous> (/home/sprtcrnbry/tools/BukanGC56/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by Pepijn98** [comment]
You need to pass options in the constructor.
The options type look like this:
https://github.com/azurlane-api/AzurLane/blob/3d77782e8cd65b2e9deb15b2a23d0a74abedf586/src/azurlane.ts#L8-L11
